nuttx/config_build_kernel: Temporarily disable link with nuttx_xx and _c
The problem is that prebuild_targets pulls in nuttx_xx (user version)
unconditionally, for both user and kernel. This in turn pulls in nuttx_c
(user version) which causes a link issue:

NuttX/nuttx/libs/libc/libc.a(pthread_attr_init.o): in function `.LANCHOR0':
NuttX/nuttx/include/nuttx/pthread.h:118: multiple definition of `g_default_pthread_attr'; NuttX/nuttx/sched/libsched.a(pthread_create.o):/home/ville/wpc_toolchain/workspace/px4-firmware/platforms/nuttx/NuttX/nuttx/include/nuttx/pthread.h:118: first defined here

This temporarily patches the issue, the real fix is to remove nuttx_xx
from prebuild_targets (which causes a ton of new issues to resolve...)