boards/xx: Add CONFIG_LIBC_NETDB=y to all configs
After some change in NuttX upstream this is not selected anymore, which
results in the following build errors:

arm-none-eabi/bin/ld: src/modules/microdds_client/lib/libmicroxrcedds_client.a(udp_transport_posix.c.obj): in function `uxr_init_udp_platform':
udp_transport_posix.c:(.text.uxr_init_udp_platform+0x36): undefined reference to `getaddrinfo'
arm-none-eabi/bin/ld: udp_transport_posix.c:(.text.uxr_init_udp_platform+0x42): undefined reference to `freeaddrinfo'